feat: add user and item Controllers
AlexsanderShchetinin/java-shareit pull request #1
Opened 2024-07-24 12:28 UTC by AlexsanderShchetinin

2024-07-24 15:11 UTC, andrew-larkin requested changes
Привет! Отличный старт! Немного доработаем приложение для удобства разработки в будущих спринтах и работа будет принята.

2024-07-24 15:11 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    Item bookingItem;
модификаторы доступа

2024-07-24 15:11 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
для этого приложения давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Все методы маппинга будут писаться в одну строчку благодаря ней, и нам это очень облегчит работу над этим приложением в ближайших спринтах

2024-07-24 15:11 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto add(@RequestHeader("X-Sharer-User-Id") String ownerId,
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.createItem(itemDto, userId));
Для всех методов во всех контроллерах стоит его добавить

2024-07-24 15:11 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Item create(Item item);
в репозиториях, которые напрямую связываются с БД, когда возвращается объект в единственном экземпляре, мы можем легко схватить NPE, если объект не будет найден. Поэтому во всех подобных случаях тип ответа стоит оборачивать в Optional. а затем в сервисе, или в реализации репозитория безопасно доставать из Optional объект с помощью метода .orElseThrow

2024-07-25 16:57 UTC, AlexsanderShchetinin commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Item create(Item item);
во всех репозиториях возвращаемые значения обернуты в Optional, если это были не списки

2024-07-25 16:57 UTC, AlexsanderShchetinin commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto add(@RequestHeader("X-Sharer-User-Id") String ownerId,
в методах контроллеров, где возвращалось какое либо значение, оно обернуто в ResponseEntity и также в return добавлен статус ответа.

2024-07-25 16:57 UTC, AlexsanderShchetinin commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Добавлена автоматическая генерация классов мапперов припомощи mapStruct, старые мапперы удалены

2024-07-25 16:57 UTC, AlexsanderShchetinin commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    Item bookingItem;
исправлено

2024-07-26 15:29 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-07-30 17:38 UTC, merged