feat: add booking and comment to item
AlexsanderShchetinin/java-shareit pull request #2
Opened 2024-08-10 18:13 UTC by AlexsanderShchetinin

2024-08-11 18:58 UTC, andrew-larkin requested changes
Привет! Хорошая и качественная реализация! Местами поправить dto и работа будет принята.

2024-08-11 18:58 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
в dto не должно быть моделей-сущностей. можно использовать либо id, либо другой dto

2024-08-11 18:58 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    private Item item;
id

2024-08-11 18:58 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
закомментированные настройки удаляем

2024-08-12 15:33 UTC, AlexsanderShchetinin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private Item item;
изменил на использование другого Dto чтобы проходили тесты

2024-08-14 18:26 UTC, andrew-larkin approved these changes
Отлично, работа принята!

2024-10-03 16:49 UTC, merged